### ISSUE TITLE
Account creation date bug

### ISSUE THREAD

**Issue by TheBooker66** [Electroid/mojang-api#46] opened 2021-09-21 18:54 UTC
The date the account was created as shown on the website doesn't match the date the account was created on Minecraft.net (It can be checked by opening your profile in minecraft.net, going to the network tab in dev tools, refreshing the page and looking at the file (?) named "namechange").
Your site: https://api.ashcon.app/mojang/v2/user/thebooker66
Mojang's site:
![image](https://user-images.githubusercontent.com/83127216/134230554-79c1db95-e337-4655-a037-fd55cb4a754b.png)

**Comment by Zeryther** [comment] 2021-10-05 08:14
Duplicate of #34

**Comment by TheBooker66** [comment] 2021-10-05 08:48
not exactly, as that issue does not mention the mojang.net method returns other results.

**Comment by Electroid** [comment] 2022-11-26 21:12
Unfortunately, Mojang has removed the ability to calculate the creation date. Past dates are cached, but we cannot generate future dates anymore.

**Closed by Electroid** 2022-11-26 21:12 UTC
